"""
SyncSketch — backend/database.py

Everything database-related in one place:
  - Async SQLAlchemy engine + session factory
  - StrokeRow ORM model
  - CRUD helpers used by ws.py and rooms.py

The rest of the app never imports SQLAlchemy directly — only this file does.
"""

from __future__ import annotations

import os
from datetime import datetime
from typing import Any

from dotenv import load_dotenv
from sqlalchemy import DateTime, Float, Text, delete, func, select
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.ext.asyncio import (
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# ─── Config ───────────────────────────────────────────────────────────────────

load_dotenv()   # reads .env in the current working directory

DATABASE_URL: str = os.environ["DATABASE_URL"]  # fail fast if not set

# ─── Engine + session factory ─────────────────────────────────────────────────

# echo=False in production; set echo=True temporarily to see raw SQL
engine = create_async_engine(DATABASE_URL, echo=False, pool_pre_ping=True)

# expire_on_commit=False keeps ORM objects usable after session.commit()
AsyncSessionLocal = async_sessionmaker(engine, expire_on_commit=False)


# ─── ORM model ────────────────────────────────────────────────────────────────

class Base(DeclarativeBase):
    pass


class StrokeRow(Base):
    """
    One completed drawing stroke.

    The id is the same short string generated by the frontend (generateId()),
    so we can match DB rows to in-memory strokes without any translation.
    """

    __tablename__ = "strokes"

    id:         Mapped[str]      = mapped_column(Text, primary_key=True)
    room_id:    Mapped[str]      = mapped_column(Text, nullable=False, index=True)
    tool:       Mapped[str]      = mapped_column(Text, nullable=False)
    color:      Mapped[str]      = mapped_column(Text, nullable=False)
    size:       Mapped[float]    = mapped_column(Float, nullable=False)
    points:     Mapped[Any]      = mapped_column(JSONB, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )


# ─── Schema management ────────────────────────────────────────────────────────

async def create_tables() -> None:
    """
    Create all tables that don't exist yet.
    Called once on server startup via the FastAPI lifespan hook.
    Safe to call on every restart — idempotent.
    """
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)


# ─── CRUD helpers ─────────────────────────────────────────────────────────────

async def load_strokes(room_id: str) -> list[dict]:
    """
    Return all strokes for a room ordered by creation time.
    Returns the same dict shape the frontend expects.
    """
    async with AsyncSessionLocal() as session:
        result = await session.execute(
            select(StrokeRow)
            .where(StrokeRow.room_id == room_id)
            .order_by(StrokeRow.created_at)
        )
        rows = result.scalars().all()
        return [
            {
                "id":     row.id,
                "tool":   row.tool,
                "color":  row.color,
                "size":   row.size,
                "points": row.points,
            }
            for row in rows
        ]


async def save_stroke(room_id: str, stroke: dict) -> None:
    """Persist a completed stroke to the database."""
    async with AsyncSessionLocal() as session:
        session.add(
            StrokeRow(
                id=stroke["id"],
                room_id=room_id,
                tool=stroke["tool"],
                color=stroke["color"],
                size=stroke["size"],
                points=stroke["points"],
            )
        )
        await session.commit()


async def delete_stroke(stroke_id: str) -> None:
    """Hard-delete a stroke by id (used by undo)."""
    async with AsyncSessionLocal() as session:
        row = await session.get(StrokeRow, stroke_id)
        if row:
            await session.delete(row)
            await session.commit()


async def clear_room(room_id: str) -> None:
    """Delete every stroke in a room (used by canvas clear)."""
    async with AsyncSessionLocal() as session:
        await session.execute(
            delete(StrokeRow).where(StrokeRow.room_id == room_id)
        )
        await session.commit()
